### ISSUE TITLE
Please help and I will help write the howto!

### ISSUE THREAD

**Issue by sebastienvg** [hypergolic/greeenwave_firmware#2]
I tried this procedure on couple machine and I get the same error (both mac and centos7) return
```
Traceback (most recent call last):
  File "https.py", line 28, in <module>
    httpd.socket = ssl.wrap_socket (httpd.socket, certfile='server.pem', server_side=True)
  File "/usr/lib64/python2.7/ssl.py", line 913, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 526, in __init__
    self._context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:2757)
```

when running python https.py making sure I have a server.pem and altered the IP in https.py 

What am I missing here?

**Comment by bren1818** [comment]
I branched this project and modified it a bit here:
https://github.com/bren1818/TCPFirmwareRestore
Might help. I had some issues as well. You may need to code the absolute path to the pem file rather than a relative.

I did mine on Windows though. Best of luck. Also be sure you block the green wave  domains so the bridge won't re upgrade itself.

Also there may be some tidbits of info in my post on this project here : 
https://github.com/hypergolic/greeenwave_firmware/issues/1

**Comment by sebastienvg** [comment]
Thank you for the hint(s) in the meantime I ended up throwing the "roxy" folder on a bare apache with ssl self-signed and it rocked my boat ;)
